### ISSUE TITLE
Newlines not displaying in display equations

### ISSUE THREAD

**Issue by ChiCubed** [lwchkg/gitbook-plugin-mathjax-commonhtml#4]
I am using a double backslash, `\\`, to indicate that a newline should be placed in my display math.

Here's an example of the issue:

<img width="300" alt="Issue" src="https://user-images.githubusercontent.com/10266947/26881011-c4acbc02-4bc8-11e7-9adf-00f80689bb54.png">

There should be a newline after the 33. For reference the code for the above is this:

```
A = \left\lfloor \frac{100}{3} \right\rfloor = 33 \\
B = \left\lfloor \frac{100}{4} \right\rfloor = 25
```

I don't think it's to do with escaping, because `\;` (a thin space) renders fine. Also, looking at the HTML source, there's a span with class `mjx-mspace` created, but it doesn't seem to do anything.

**Comment by pkra** [comment]
Filed upstream at https://github.com/mathjax/MathJax-node/issues/335

**Comment by lwchkg** [comment]
@pkra Thanks for following the project and filing the bug upstream. I agree with your analysis there.

**Comment by pkra** [comment]
This was fixed upstream.
